### PR TITLE
Added Sound Position and Surround

### PR DESCRIPTION
**Pull request by andro2157**
I added the sound position.

I could only test this on Windows using Sony WH-XB900N (btw it works perfectly fine on it! good job!), but the command seems to be the same for every headset in the app so I guess that this should work fine.

### CODE REVIEW

**Comment by andro2157** [comment]
I also added the Surround while we're at it since it's the same command.

I added these two options in a new collapsing header called "Virtual Sound" (don't know how to call this).

**Comment by Plutoberth** [comment]
Awesome! I'm planning to merge the Qt branch soon (next week or a bit later probably), so could you adapt it to it after it's merged?

**Comment by andro2157** [comment]
Sure!

**Comment by Arcant1** [comment]
Awesome repo, can we have an update about this? Thanks!

**Comment by Plutoberth** [comment]
Thank you.

**Comment by EduardCM** [comment]
> @Arcant1 merged :)

Is the Sound Position/VPT a windows only feature? On the macOS version (v.13 from the release page) there is no new options available other than ambient sound related ones.

**Comment by EduardCM** [comment]
> @EduardCM
> 
> It is currently an open pull request #73, but already working.
> 
> Compiled binary (might require login): https://github.com/Plutoberth/SonyHeadphonesClient/suites/6833272259/artifacts/263310936

Oh, I can confirm this one works, thanks!

The one from here https://github.com/Plutoberth/SonyHeadphonesClient/releases/download/v1.3/SonyHeadphonesClient-macOS.zip.zip must be an old binary. The one you linked is 109kb, the one I linked is 99kb.

**Comment by Plutoberth** [comment]
> > @EduardCM
> > It is currently an open pull request #73, but already working.
> > Compiled binary (might require login): https://github.com/Plutoberth/SonyHeadphonesClient/suites/6833272259/artifacts/263310936
> 
> Oh, I can confirm this one works, thanks!
> 
> The one from here https://github.com/Plutoberth/SonyHeadphonesClient/releases/download/v1.3/SonyHeadphonesClient-macOS.zip.zip must be an old binary. The one you linked is 109kb, the one I linked is 99kb.

Awesome. I kinda forgot about the PR - I'll take a look and merge now.

**Pull request merged**
