### PR TITLE
Add option to turn off NC and ambient sound

### LINKED ISSUE #18: Option to turn off NC and ambient sound
Really like the program, but I don't see any option to turn off both NC and ambient sound. It's useful if you want to save battery on the headphones. In the Android app, you can do this by turning off the "Ambient Sound Control" toggle.

nc_asm_off

### PR DESCRIPTION
**Pull request by guilhermealbm**
This fixes #18. After taking a look over bluetooth messages, found out that ambient sound control is turned off when sending vol=-1.

The only problem I faced is when checking and, after, unchecking the box. It returns a "Invalid checksum!". Same happens when do it at "Focus on Voice" checkbox, so I think that's maybe a problem with XM4's (and not my changes), as other people said in #27.

I tested it in XM4's and Windows. Hope it helps! :)

### CODE REVIEW

**Comment by semvis123** [comment]
Hey I might be wrong on this one, but to me it looks like `NC_ASM_EFFECT::OFF` should be used to turn off the ambient sound control. This turns it off for me, on a WH-1000XM3.

**Comment by semvis123** [comment]
I have updated the macOS version to have the same functionality.
[Compiled version](https://github.com/Plutoberth/SonyHeadphonesClient/files/6111333/SonyHeadphonesClient.zip)

**Comment by Plutoberth** [comment]
@guilhermealbm which method did you use to fetch the messages between your phone and the headset? Did you hook the relevant function  using Frida or something? I didn't manage to get it to work using the sniffer Android provides. I'll probably merge this this weekend, BTW.

**Comment by guilhermealbm** [comment]
Hi @Plutoberth! I started trying logging with [Bluetooth HCI Snoop](https://source.android.com/devices/bluetooth/verifying_debugging#debugging-with-logs) and analyzing it with Wireshark, but was extremely confusing. So, I discovered that my device has a [logkit](https://forum.xda-developers.com/t/sdcard-btsnoop_hci-log-not-found.3753907/post-77090858).

It generates a really big file, but I filtered by my XM4's MAC and found the event logs;
For example, when I toggle the "Ambient Sound Control" button, it records:

```
03-08 23:00:17:503 handleBluetoothA2dpActiveDeviceChangeExt  state=2 addr=[...] prof=2 supprNoisy=true vol=18
03-08 23:00:17:504 setBluetoothA2dpDeviceConnectionStateSuppressNoisyIntent  state=2 addr=[...] prof=2 supprNoisy=true vol=18
03-08 23:00:17:506 A2DP sink connected: device addr=[...] state=2 vol=18
03-08 23:00:20:405 handleBluetoothA2dpActiveDeviceChangeExt  state=0 addr=[...] prof=2 supprNoisy=false vol=-1
03-08 23:00:20:405 setBluetoothA2dpDeviceConnectionStateSuppressNoisyIntent  state=0 addr=[...] prof=2 supprNoisy=false vol=-1
```

I ommited my mac addr, but, in general, that's it! 😃

**Comment by Plutoberth** [comment]
> 
> 
> Hi @Plutoberth! I started trying logging with [Bluetooth HCI Snoop](https://source.android.com/devices/bluetooth/verifying_debugging#debugging-with-logs) and analyzing it with Wireshark, but was extremely confusing. So, I discovered that my device has a [logkit](https://forum.xda-developers.com/t/sdcard-btsnoop_hci-log-not-found.3753907/post-77090858).
> 
> It generates a really big file, but I filtered by my XM4's MAC and found the event logs;
> For example, when I toggle the "Ambient Sound Control" button, it records:
> 
> ```
> 03-08 23:00:17:503 handleBluetoothA2dpActiveDeviceChangeExt  state=2 addr=[...] prof=2 supprNoisy=true vol=18
> 03-08 23:00:17:504 setBluetoothA2dpDeviceConnectionStateSuppressNoisyIntent  state=2 addr=[...] prof=2 supprNoisy=true vol=18
> 03-08 23:00:17:506 A2DP sink connected: device addr=[...] state=2 vol=18
> 03-08 23:00:20:405 handleBluetoothA2dpActiveDeviceChangeExt  state=0 addr=[...] prof=2 supprNoisy=false vol=-1
> 03-08 23:00:20:405 setBluetoothA2dpDeviceConnectionStateSuppressNoisyIntent  state=0 addr=[...] prof=2 supprNoisy=false vol=-1
> ```
> 
> I ommited my mac addr, but, in general, that's it! 😃

Wow, so this format is standardized? I was 100% sure it was proprietary. This is really great news for future features. I have a Oneplus too so I'll check this out when I have some time.

**Review by Plutoberth — CHANGES_REQUESTED** [review]
Hi, looks great, just one small request - could you make it so the text "Focus on voice isn't enabled on this level" isn't shown if ambient sound is disabled?
image

**Comment by guilhermealbm** [comment]
> Wow, so this format is standardized? I was 100% sure it was proprietary. This is really great news for future features. I have a Oneplus too so I'll check this out when I have some time.

I don't think it's a standardized format. Fortunately, toggling NC button also calls android's `handleBluetoothA2dpActiveDeviceChangeExt`and `setBluetoothA2dpDeviceConnectionStateSuppressNoisyIntent` methods, which are recorded by OnePlus logkit. For example, alternating between equalizer profiles doesn't generate any record at log file 😕

I was not sure why this happens too, but [Galaxy Buds Client](https://github.com/ThePBone/GalaxyBudsClient#how-it-works) explains it very well. To certain features, reverse-engineer the data format is the only alternative.

**Comment by guilhermealbm** [comment]
> Hi, looks great, just one small request - could you make it so the text "Focus on voice isn't enabled on this level" isn't shown if ambient sound is disabled?
> image

I really didn't notice that! Just fixed :smile:

**Comment by Plutoberth** [comment]
LGTM, merged :)

**Pull request merged**
