### PR TITLE
Updated macOS version to support the off mode

### PR DESCRIPTION
**Pull request by semvis123**
This pull request requires the changes from #36
image

[Compiled version](https://github.com/Plutoberth/SonyHeadphonesClient/files/6111333/SonyHeadphonesClient.zip)

### CODE REVIEW

**Comment by Plutoberth** [comment]
Not that it matters, but why do you zip the app before uploading it?

**Comment by Plutoberth** [comment]
Did you verify that the resulting binary works?

**Comment by semvis123** [comment]
> Not that it matters, but why do you zip the app before uploading it?
> 
> Edit: nvm, the original .app is a folder, not a file

That's because of the way macOS downloads files, if I didn't zip the .app, safari would auto unzip/convert the .app to a folder named contents.

> Did you verify that the resulting binary works?

My current headphones are in service, so I can't test the functionality binary, however the binary does launch just fine.

**Comment by Plutoberth** [comment]
I see, so I'm merging this and creating a new release with everything.

**Comment by semvis123** [comment]
Oh so it’s a double zip now... 
Maybe it shouldn’t zip another time in the release?

**Comment by Plutoberth** [comment]
I don't think that's possible because of how Github packages artifacts... Doesn't really matter anyway 🤷🏼‍♂️

**Pull request merged**
